# Build runner script:
# dart run build_runner watch

name: apple
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  logger: ^2.3.0
  material_design_icons_flutter: ^7.0.7296
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^8.2.0

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
